# 生产环境配置
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/water_management?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: your_production_password
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50

logging:
  level:
    root: WARN
    com.waterworks: INFO


