# 生产环境配置
server:
  port: 8080

spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/water_management?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
      username: root
      password: your_production_password

logging:
  level:
    root: WARN
    com.waterworks: INFO


